/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blackjackclient;

/**
 *
 * @author ambitos
 */
public class BlackjackClientJFrame extends javax.swing.JFrame {

    /**
     * Creates new form BlackjackClientJFrame
     */
    public BlackjackClientJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dealJButton = new javax.swing.JButton();
        hitJButton = new javax.swing.JButton();
        standJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dealerCard1JLabel = new javax.swing.JLabel();
        dealerCard2JLabel = new javax.swing.JLabel();
        dealerCard3JLabel = new javax.swing.JLabel();
        dealerCard4JLabel = new javax.swing.JLabel();
        dealerCard11JLabel = new javax.swing.JLabel();
        dealerCard6JLabel = new javax.swing.JLabel();
        dealerCard7JLabel = new javax.swing.JLabel();
        dealerCard8JLabel = new javax.swing.JLabel();
        dealerCard9JLabel = new javax.swing.JLabel();
        dealerCard10JLabel = new javax.swing.JLabel();
        dealerCard5JLabel = new javax.swing.JLabel();
        playerCard1JLabel = new javax.swing.JLabel();
        playerCard1JLabel1 = new javax.swing.JLabel();
        playerCard1JLabel2 = new javax.swing.JLabel();
        playerCard1JLabel3 = new javax.swing.JLabel();
        playerCard1JLabel4 = new javax.swing.JLabel();
        playerCard1JLabel5 = new javax.swing.JLabel();
        playerCard1JLabel6 = new javax.swing.JLabel();
        playerCard1JLabel7 = new javax.swing.JLabel();
        playerCard1JLabel8 = new javax.swing.JLabel();
        playerCard1JLabel9 = new javax.swing.JLabel();
        playerCard1JLabel10 = new javax.swing.JLabel();
        gameResultsJLabel = new javax.swing.JLabel();
        dealerJLabel = new javax.swing.JLabel();
        dealerScoreJLabel = new javax.swing.JLabel();
        playerJLabel = new javax.swing.JLabel();
        playerScoreJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dealJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dealJButton.setText("Deal");

        hitJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hitJButton.setText("Hit");

        standJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        standJButton.setText("Stand");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Dealer's hand:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Player's hand:");

        dealerCard1JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N
        dealerCard1JLabel.setToolTipText("");

        dealerCard2JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N

        dealerCard3JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N

        dealerCard4JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N

        dealerCard11JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N

        dealerCard6JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N

        dealerCard7JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N

        dealerCard8JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N

        dealerCard9JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N

        dealerCard10JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N

        dealerCard5JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N

        playerCard1JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N
        playerCard1JLabel.setToolTipText("");

        playerCard1JLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N
        playerCard1JLabel1.setToolTipText("");

        playerCard1JLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N
        playerCard1JLabel2.setToolTipText("");

        playerCard1JLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N
        playerCard1JLabel3.setToolTipText("");

        playerCard1JLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N
        playerCard1JLabel4.setToolTipText("");

        playerCard1JLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N
        playerCard1JLabel5.setToolTipText("");

        playerCard1JLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N
        playerCard1JLabel6.setToolTipText("");

        playerCard1JLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N
        playerCard1JLabel7.setToolTipText("");

        playerCard1JLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N
        playerCard1JLabel8.setToolTipText("");

        playerCard1JLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N
        playerCard1JLabel9.setToolTipText("");

        playerCard1JLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackjackclient/images/1c.png"))); // NOI18N
        playerCard1JLabel10.setToolTipText("");

        gameResultsJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gameResultsJLabel.setText("Blackjack!");

        dealerJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dealerJLabel.setText("Dealer:");

        dealerScoreJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dealerScoreJLabel.setText("17");

        playerJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        playerJLabel.setText("Player:");

        playerScoreJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        playerScoreJLabel.setText("21");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(playerCard1JLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playerCard1JLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playerCard1JLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playerCard1JLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playerCard1JLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playerCard1JLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(playerCard1JLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playerCard1JLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playerCard1JLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playerCard1JLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playerCard1JLabel10)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dealerCard1JLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dealerCard2JLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dealerCard3JLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dealerCard4JLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dealerCard5JLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dealerCard6JLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dealerCard7JLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dealerCard8JLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dealerCard9JLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dealerCard10JLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dealerCard11JLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gameResultsJLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(hitJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dealJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(standJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dealerJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dealerScoreJLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(playerJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playerScoreJLabel)))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dealerCard1JLabel)
                                        .addComponent(dealerCard2JLabel))
                                    .addComponent(dealerCard3JLabel)
                                    .addComponent(dealerCard4JLabel)
                                    .addComponent(dealerCard6JLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dealerCard8JLabel)
                                    .addComponent(dealerCard7JLabel)
                                    .addComponent(dealerCard9JLabel)
                                    .addComponent(dealerCard10JLabel)
                                    .addComponent(dealerCard11JLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dealJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(standJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54)
                        .addComponent(gameResultsJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dealerJLabel)
                            .addComponent(dealerScoreJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(playerJLabel)
                            .addComponent(playerScoreJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerCard1JLabel)
                            .addComponent(playerCard1JLabel1)
                            .addComponent(playerCard1JLabel2)
                            .addComponent(playerCard1JLabel3)
                            .addComponent(playerCard1JLabel4)
                            .addComponent(playerCard1JLabel5))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerCard1JLabel7)
                            .addComponent(playerCard1JLabel6)
                            .addComponent(playerCard1JLabel8)
                            .addComponent(playerCard1JLabel9)
                            .addComponent(playerCard1JLabel10))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dealerCard5JLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlackjackClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlackjackClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlackjackClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlackjackClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlackjackClientJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dealJButton;
    private javax.swing.JLabel dealerCard10JLabel;
    private javax.swing.JLabel dealerCard11JLabel;
    private javax.swing.JLabel dealerCard1JLabel;
    private javax.swing.JLabel dealerCard2JLabel;
    private javax.swing.JLabel dealerCard3JLabel;
    private javax.swing.JLabel dealerCard4JLabel;
    private javax.swing.JLabel dealerCard5JLabel;
    private javax.swing.JLabel dealerCard6JLabel;
    private javax.swing.JLabel dealerCard7JLabel;
    private javax.swing.JLabel dealerCard8JLabel;
    private javax.swing.JLabel dealerCard9JLabel;
    private javax.swing.JLabel dealerJLabel;
    private javax.swing.JLabel dealerScoreJLabel;
    private javax.swing.JLabel gameResultsJLabel;
    private javax.swing.JButton hitJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel playerCard1JLabel;
    private javax.swing.JLabel playerCard1JLabel1;
    private javax.swing.JLabel playerCard1JLabel10;
    private javax.swing.JLabel playerCard1JLabel2;
    private javax.swing.JLabel playerCard1JLabel3;
    private javax.swing.JLabel playerCard1JLabel4;
    private javax.swing.JLabel playerCard1JLabel5;
    private javax.swing.JLabel playerCard1JLabel6;
    private javax.swing.JLabel playerCard1JLabel7;
    private javax.swing.JLabel playerCard1JLabel8;
    private javax.swing.JLabel playerCard1JLabel9;
    private javax.swing.JLabel playerJLabel;
    private javax.swing.JLabel playerScoreJLabel;
    private javax.swing.JButton standJButton;
    // End of variables declaration//GEN-END:variables
}
